### ISSUE TITLE
MafAnnotator.py gives error "AttributeError: 'ProteinChangeQuery' object has no attribute 'proteinStart'" when input MAF contains non-coding mutations and -q "HGVSp" is specified

### ISSUE THREAD

**Issue by bkinnersley** [oncokb/oncokb-annotator#124]
Hello,

I am interested in using MafAnnotator.py to annotate MAF files from tumour whole genome sequencing, e.g. using example command:

python MafAnnotator.py \
-i <input_maf> \
-o <output_maf> \
-b <example_token> \
-r "GRCh38" -t "COADREAD" -a -g "HGVSp" 

I have a few queries:
1. Currently by using -q "HGVSp" or -q "HGVSp_short" will cause MafAnnotator.py to quit with the following error "AttributeError: 'ProteinChangeQuery' object has no attribute 'proteinStart'" if the input MAF has not been pre-filtered to remove non-coding mutations (which have an empty "HGVSp" annotation) - is this expected? If the MAF only contains coding mutations/HGVSp annotations this error does not occur.
2. There is reference to "Alteration" as an annotation that can be provided in the input MAF as an alternative to HGVSp, but I cannot find much documentation on this (it is not in https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/ for example) - would it be possible to get more information on the "Alteration" input mutation annotation?
3. If I switched to -q "Genomic_Change" to annotate mutations, would this enable annotation of potentially clinically actionable non-coding mutations that would not have an HGVSp annotation (e.g. TERT promoter mutation, as well as mutations in essential splice sites) - would this therefore be recommended (other than as mentioned being more time-consuming)?

Thanks very much!

Best wishes

Ben

**Comment by zhx828** [comment]
@bkinnersley sorry about the late reply. Just saw your issue. Do you mind share the input files of yours so that I can take a look? My testing cases probably not good enough to find out the bug in my code.

For the genomic location changes, yes and no. Yes, it can transcript non-coding mutations. OncoKB is able to annotate TERT promoter because it's an upstream_gene_variant. But OncoKB is not sophisticated enough to annotate atypical variants like EGFR vIII, Kinase Domain Duplication through genomic changes. For these atypical ones, you have to use the protein change endpoint https://api.oncokb.org/oncokb-website/api#atypical-alterations

**Comment by zhx828** [comment]
This issues should be solved in https://github.com/oncokb/oncokb-annotator/pull/128. Closing the ticket, please let me know if you have any questions.
