### ISSUE TITLE
MYCN mutations is annotated as unknown

### ISSUE THREAD

**Issue by andreyurch** [oncokb/oncokb-annotator#48]
Dear developers,

Thank you for the very useful tool!
I found that highly recurrent MYCN P44L mutation is annotated as Unknown, while it is present in oncoKB (https://www.oncokb.org/gene/MYCN).  Please find attached my annotated MAF file.

Best regards,
[Mycn_example.txt](https://github.com/oncokb/oncokb-annotator/files/4440830/Mycn_example.txt)

Andrey

**Comment by zhx828** [comment]
@andreyurch we do not support `Protein_Change` as the header. Please use `HGVSP_SHORT`.
@jjgao `Protein_Change` seems to be a frequently used header. Should we support it?

**Comment by andreyurch** [comment]
@zhx828 
Thank you for the information, but I had hundreds of variants with my headers and the majority of them were correctly annotated (Oncogenic..). I found the error only with MYCN.

**Comment by zhx828** [comment]
@andreyurch if you don't mind, could you share few that has information? I want to double check the result.

**Comment by andreyurch** [comment]
@zhx828 please find attached a part of annotated mutations. They were in the same file with MYCN


[Example_oncokb.txt](https://github.com/oncokb/oncokb-annotator/files/4457333/Example_oncokb.txt)

**Comment by zhx828** [comment]
@andreyurch the result is what I expected. Majority of your data are generally truncated. And you have the `Variant_Classification` column defined. Use the first row `ATR` as example, since the annotator cannot get the alteration, then it does annotation for an alteration in ATR that generally truncated(we map Nonsense_Mutation to stop_gained). And OncoKB does curate Truncating Mutations in ATR as Likely Oncogenic. That's why in the citations column, they are for Truncating Mutations too. But I do curious how `ATM p.I323V`  gets annotated to Likely Oncogenic, it also gets the citations from Truncating Mutations.

But for now, I think you should change the header to get the accurate result. I will discuss with the team whether to support Protein_Change as header name.
